# Generated by Django 2.2 on 2024-02-20 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('golf', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('room', models.CharField(max_length=50)),
                ('time', models.CharField(max_length=50)),
                ('home', models.CharField(max_length=50)),
            ],
        ),
    ]
